[phases.setup]
nixPkgs = ["zlib", "libjpeg", "freetype", "lcms2", "openjpeg", "libimagequant", "libwebp", "tcl", "tk", "harfbuzz", "fribidi", "ghostscript", "pkg-config", "python311Packages.pillow"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]
