[phases.setup]
nixPkgs = ["zlib", "libjpeg", "freetype", "lcms2", "openjpeg", "libimagequant", "libwebp", "tcl", "tk", "harfbuzz", "fribidi", "ghostscript", "pkgconfig", "python311Packages.pillow"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]
